"""Init db v2

Revision ID: 483559b6395e
Revises: 
Create Date: 2026-05-16 00:12:22.360840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483559b6395e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etablissements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('type_abonnement', sa.String(length=20), nullable=False),
    sa.Column('date_expiration', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('est_demo', sa.Boolean(), nullable=True),
    sa.Column('devise', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('montant_inscription', sa.Float(), nullable=False),
    sa.Column('montant_scolarite', sa.Float(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('eleves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('nom_parent', sa.String(length=100), nullable=True),
    sa.Column('email_parent', sa.String(length=120), nullable=True),
    sa.Column('classe_id', sa.Integer(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('date_paiement', sa.DateTime(), nullable=True),
    sa.Column('type_paiement', sa.String(length=20), nullable=False),
    sa.Column('motif', sa.String(length=200), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paiements')
    op.drop_table('eleves')
    op.drop_table('utilisateurs')
    op.drop_table('classes')
    op.drop_table('etablissements')
    # ### end Alembic commands ###
