"""Ajout colonne caissier pour audit

Revision ID: 6c3ba3faadc3
Revises: 483559b6395e
Create Date: 2026-05-16 00:25:50.587820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3ba3faadc3'
down_revision = '483559b6395e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enregistre_par_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_paiements_enregistre_par_id', 'utilisateurs', ['enregistre_par_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('enregistre_par_id')

    # ### end Alembic commands ###
