"""Ajout code secret parent

Revision ID: dcb660cf1536
Revises: 6c3ba3faadc3
Create Date: 2026-05-16 01:07:57.672964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb660cf1536'
down_revision = '6c3ba3faadc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eleves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_parent', sa.String(length=15), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_eleves_code_parent'), ['code_parent'])

    with op.batch_alter_table('etablissements', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_etablissements_email'), ['email'])

    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_utilisateurs_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_utilisateurs_email'), type_='unique')

    with op.batch_alter_table('etablissements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_etablissements_email'), type_='unique')

    with op.batch_alter_table('eleves', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_eleves_code_parent'), type_='unique')
        batch_op.drop_column('code_parent')

    # ### end Alembic commands ###
